[package]
name = "mkl82z7-pac"
version = "0.1.1"
authors = ["Sindre Hansen <sindrehansen92@gmail.com>"]
edition = "2018"

[dependencies]
bare-metal = "1.0.0"
vcell = "0.1.3"
cortex-m = "0.7.3"

[dependencies.cortex-m-rt]
optional = true
version = "0.7.0"

[features]
rt = ["cortex-m-rt/device"]
